# Generated by Django 3.1.4 on 2020-12-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='lyrics',
            field=models.CharField(default="prove it feels right out on me drop on them back road in them back then you paint your hand to worship you can still\nsomebody's worst night\nthe miracle that they love\nand i'll never be another\n\n\nkinda funny how lucky i quit\n\n\nkinda wanna let the almost so you sugar just here in line early to here with you used to remember\nyour eyes\nthat your shade of coke in a hole in my family thought\nyeah\nwe pickin' on my money\nsomebody's problem and to you that you're still in and outta my knees\nwill ", max_length=10000),
        ),
        migrations.AlterField(
            model_name='pop',
            name='lyrics',
            field=models.CharField(default="45 when i'm levitating\nshit that afro hairdo\n\n   \njust relax just let me tonight\nwhen shit maybe when i feel fine\ndadadadadada oh\nnow\n\n \nor anything damn\ngirl it's a willow and i tried to\n\n\nyou got me girl\nthen make a mood? fuckin 'round actin' brand new\ni'll be brave see it for a rocket watch that to the look baby let you baby\nfightin' for you baby let them babies\ni caught your friend\nladadaduhduh baby i lost in the coupe woke up up\nwe're a penthouse near rodeo off the ", max_length=10000),
        ),
        migrations.AlterField(
            model_name='rap',
            name='lyrics',
            field=models.CharField(default="wear my label every single\nand said my voice just playin' in the imitation man\nthis is told 'em the chicken wang mgk igg' azae'\nbut i hear the bruce lee ah\nbut he makin' mommy sad even stomach\noohooh wee bit with my nordictrack\nand laugh\nhe goes on tv and i would you look what happens for comin' through no\nyou only get me and burst in my two hundred you could vent to bring the streets\nyou don't know that yeah call up stretch out as a feeling i've been alone stand up and pay 'cause he ", max_length=10000),
        ),
        migrations.AlterField(
            model_name='rock',
            name='lyrics',
            field=models.CharField(default="wake if i feel heavy metal\npleased to the blackboard\n\n\n\n\noh yeah yeah yeah yeah\nand drive?\nwould you\n\n  \nhe hit me dry\nwill she cares\n\n \ni'll take me dry\n\n  \nturn the lord my violence melody shine let you will not my libido\n\n\ni am i don't speak i forget my libido\n\n \nall\ncool\n\n\ni don't believe that everyone else gets around\nblack hole sun\ngot a thousand guilts\nin\nto find that will until the dogs do it\nour memories well don't need you kill ", max_length=10000),
        ),
        migrations.AlterField(
            model_name='xmas',
            name='lyrics',
            field=models.CharField(default="sweet the cold outside!\nit's really care about the first thing\nand caroling late night\n\n\ngo glidin' in my wish we could forget what a simple phrase\nwe'll do do do do a pear tree\nhave a partridge in the snow let it snow let it\ni'm all over your journey\noh do do\n\n \nhow can we ain't holding me\nwas something 'bout the top\ndon't see\n\n\neveryday every mistletoe\n\n\nand\nsanta's gon' come and make him you'll check every wish come down\nsanta's gon' come on holy ground is precious\nbut now i want ", max_length=10000),
        ),
    ]
