# Generated by Django 3.1.4 on 2020-12-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201211_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='length',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pop',
            name='length',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='rap',
            name='length',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='rock',
            name='length',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='xmas',
            name='length',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='pop',
            name='lyrics',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
