# Generated by Django 3.1.4 on 2020-12-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201211_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
