# Generated by Django 3.1.4 on 2020-12-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pop_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pop',
            name='test',
        ),
        migrations.AlterField(
            model_name='pop',
            name='lyrics',
            field=models.CharField(default="someone else babe\n'cause it\nall night? can fly away from fifty i can't forget you know back to do shit is let me go?\n\n\nwon't do i what that song 'cause you're not leaving\ni need 'em my my mind\nwe try to find paradise\n\n\ni got you think that i follow\nlet me and lonely\n45 when we at midnight\nmismatched fits that i wanna run away from the biggest damn\nyou get what that you no no rat no no no i play guitars yeah\ni follow\nprisoner prisoner prisoner prisoner prisoner prisoner locked up ", max_length=10000),
        ),
    ]
