# Generated by Django 3.1.4 on 2020-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201211_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pop',
            name='lyrics',
            field=models.CharField(default="sneakin' in a stack on a mood? fuckin 'round actin' brand new\ni break?\ni'm running out of runnin' with me of my mind you had to take a nigga head in the monster?\nohoh woah ohoh woah ohoh woah\ni've been on my war ways war ways war ways war ways\ncookin' in the bedroom\ni'm sorry\nprisoner prisoner locked up\nthe night come around and she say it now i can't stop what did you remain unremarkable got the dark has gone\n\n\nyou\n\n\ngirl you why guess i was fifteen i had nothing\ni am\nshe ", max_length=10000),
        ),
    ]
