# Generated by Django 3.1.4 on 2020-12-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201211_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tag',
            field=models.IntegerField(default=1),
        ),
    ]
